INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('91679210', '20 leguas de viaje submarino', '200', 'Acantilado');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('3362398', 'De la tierra a la luna', '300', 'Acantilado');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('153498214', 'El castillo de los Carpatos', '158', 'Acantilado');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('120778212', 'Drácula', '250', 'Acantilado');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('10606345', 'El padrino', '254', 'Altea');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('183861911', 'La casa de las dos palmas', '300', 'Altea');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('193291785', 'Frutos de mi tierra', '154', 'Altea');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('150927636', 'El testamento del paisa', '400', 'Babel');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('98862798', 'La marquesa de Yolombo', '200', 'Planeta');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('79620954', 'El conde de Montecristo', '158', 'Planeta');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('96371970', 'El tulipan negro', '140', 'Planeta');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('89427792', '1984', '220', 'Babel');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('71625169', 'Rebelión en la granja', '100', 'Babel');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('195647355', 'Crimen y castigo', '300', 'Planeta');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('197457990', 'La Eneida', '150', 'Planeta');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('193347930', 'La Iliada', '150', 'Acantilado');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('85124527', 'Los venenos de la corona', '180', 'Babel');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('175499761', 'Tormenta de espadas', '450', 'Acantilado');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('189799297', 'Danza de dragones', '450', 'Planeta');
INSERT INTO libreriabuscalibre.libro (ISBN, titulo, numero_paginas, nombre_editorial) VALUES ('153951522', 'El Silmarillion', '300', 'Planeta');
